// features:
// - pack n 2d (1-4 channel) images int a string of containing images
// - can create groupings of images that should ideally stay together
// - can use glTF module to combine glTF assets
// - a few scaling options
// - output single binary file
// - load images with this data:
//     - []image: bytes, width, height, stride
//     - []texture: image index, uv rect, asset information
// - 
