add_mesh :: (renderer: *Renderer, mesh: *Mesh, in_ref: *Mesh_Ref = null) -> Mesh_Ref {
    scope_set_renderer(renderer);
    using context.renderer;

    ref: *Mesh_Ref;
    local_ref: Mesh_Ref;

    if in_ref != null {
        ref = in_ref;
    } else {
        ref = *local_ref;
    }

    array_add(*meshes, mesh.*);
    mesh_in_array := *meshes[meshes.count-1];

    for *buf : mesh_in_array.texture_buffers {
        buf.gpu_allocation = -1;
    }

    texture_counter: int;

    found_static_mesh_section: bool;
    found_skinned_mesh_section: bool;

    for *anim, ai : mesh_in_array.skeleton.animations {
        for ref.playback {
            if it.animation == ai {
                anim.speed = it.speed;
                break;
            }
        }
        if anim.speed == 0 {
            anim.speed = 1;
        }
    }

    // todo: free vertices & indices?
    for *section : mesh_in_array.sections {
        {
            using section.indices;
            if type == .U16 {
                auto_release_temp();
                assert(cpu_allocation._u16.count == count);
                // all indices are converted to u32 so the can all go in a single buffer.
                temp_u32_buffer := make_static_array(u32, count,, temp);
                for 0..cpu_allocation._u16.count-1 {
                    temp_u32_buffer[it] = cpu_allocation._u16[it];
                }
                create_gpu_index_buffer(*gpu_allocation, temp_u32_buffer);
            } else {
                assert(cpu_allocation._u32.count == count);
                create_gpu_index_buffer(*gpu_allocation, cpu_allocation._u32);
            }
        }
        {
            using section.vertices;
            if type == .STATIC {
                assert(cpu_allocation.static.count == count);
                // all sections must be either static or skinned, for simplicity. renderer requires it.
                assert(!found_skinned_mesh_section); 
                create_gpu_vertex_buffer(*gpu_allocation, cpu_allocation.static);
                found_static_mesh_section = true;
            } else {
                assert(cpu_allocation.skinned.count == count);
                // all sections must be either static or skinned, for simplicity. renderer requires it.
                assert(!found_static_mesh_section);

                // forcing normalization of skinning weights
                for *vertex : cpu_allocation.skinned {
                    vertex.color.a = 0.5;
                    sum := 0.0;
                    for *weight : vertex.weights {
                        weight.* = max(weight.*, 0);
                        sum += weight.*;
                    }
                    if sum > 0 {
                        inv_sum := 1.0 / sum;
                        for *weight : vertex.weights {
                            weight.* *= inv_sum;
                        }
                    }
                }

                create_gpu_skinned_vertex_buffer(*gpu_allocation, cpu_allocation.skinned);
                found_skinned_mesh_section = true;
            }
        }

        upload_texture(*section.material.albedo_texture, mesh_in_array, *texture_counter);
        upload_texture(*section.material.normal_texture, mesh_in_array, *texture_counter);
        upload_texture(*section.material.emissive_texture, mesh_in_array, *texture_counter);
        upload_texture(*section.material.orm_texture, mesh_in_array, *texture_counter);

        // todo: the material is stored twice. this is annoying. fix it!
        // also index type misalignment
        section.material.user_data = xx allocate_material(*section.material);
    }

    ref.index = xx (meshes.count - 1);
    return ref.*;
}

#scope_file

upload_texture :: (using tex: *Texture, mesh: *Mesh, counter: *int) {
    if local_buffer != -1 {
        buffer := *mesh.texture_buffers[local_buffer];

        // todo: texture buffer sharing with filtering per-texture
        if buffer.gpu_allocation != -1 {
            global_buffer = buffer.gpu_allocation;
            return;
        }

        counter.* += 1;

        sampler := get_or_add_sampler(min_filter, mag_filter, horizontal_wrap, vertical_wrap);

        // assuming all textures are unique -> adding one buffer per texture
        // assert(buffer.gpu_allocation == -1);

        buffer.gpu_allocation = add_gpu_image_for_sampling(buffer.cpu_allocation.data, buffer.width, buffer.height, sampler).pool_index;
        global_buffer = buffer.gpu_allocation;

        stbi_image_free(buffer.cpu_allocation.data);
        buffer.cpu_allocation.data = null;
        buffer.cpu_allocation.count = 0;
    } else {
        global_buffer = -1;
    }
}
